### ISSUE TITLE
Some paths are badly converted

### ISSUE THREAD

**Issue by maltaisn** [maltaisn/swf-convert#1]
The program sometimes fail to convert some paths to the intermediate representation, so both SVG and PDF are affected.

This seems to be a common problem in many applications that convert SWF to SVG. The algorithm used by swf-convert was copied from the one used by as3swf. The result is that [this file](https://drive.google.com/uc?export=download&id=1FTPCm6DD_bmGT3iGAjtFpCJBf97giPvP) gets converted to the path seen in the first image (viewed from Inkscape with added stroke) while the second image is the expected output (viewed from Flash Player or Lightspark).

<img src="https://i.stack.imgur.com/TzoNf.png" width="400"/>
<img src="https://i.stack.imgur.com/oHhQL.png" width="400"/>

I searched for another algorithm, however all of the following open source programs produce the same wrong output:

- [as3swf](https://github.com/claus/as3swf/blob/master/src/com/codeazur/as3swf/exporters/SVGShapeExporter.as), gives the output above.
- [ffdec](https://github.com/jindrapetrik/jpexs-decompiler/blob/bf2a413725c09eecded4e8f42af4487ecd1842a5/libsrc/ffdec_lib/src/com/jpexs/decompiler/flash/exporters/shape/ShapeExporterBase.java), seems to be based on as3swf, shapes displayed in the program are wrong too. An issue is opened [here](https://www.free-decompiler.com/flash/issues/1570-bad-shape-rendering-in-preview).
- [Flash2SVG](https://stackoverflow.com/a/21256104/5288316), getting wrong paths too.
- [pyswf](https://github.com/timknip/pyswf), again, similar output.
- The algorithm described in the [Swiffy thesis](https://pdfs.semanticscholar.org/370d/36a37c018bfe740cbd8eaa8382c03324333c.pdf) looks a lot like the one used in as3swf.

I also asked for help on [StackOverflow](https://stackoverflow.com/questions/60572635). It's entirely possible that there's currently no program able to reliably convert SWF shapes to SVG, in which case this issue will pretty much exist forever.

**Comment by jindrapetrik** [comment]
Hi, I am not sure, but I think I fixed the issue in FFdec - see the issue in its tracker.

**Comment by maltaisn** [comment]
Thanks a lot! I fixed it here and it seems to work pretty great. Also congrats on the recent progress on FFdec, I see it's been going pretty fast for the past two months.

**Comment by pendave** [comment]
<img width="901" height="729" alt="Image" src="https://github.com/user-attachments/assets/91bb8e19-5f57-4b74-b2a4-9558b5bb0b4b" />

I write a Python script to convert SWF 2 SVG, and I test the sample of yours.
It's wroking well here.
