### ISSUE TITLE
Comma in the output file name

### ISSUE THREAD

**Issue by arkbene** [maltaisn/swf-convert#3]
When running:

java -jar swf-convert.jar pdf "$SWF" -o "$PDF" -t "$TMPDIR"

where $SWF is a single file name and $PDF is also a single file name that contains a comma,
swf-convert exits with:

ERROR: Expected as many output files or directories as input.

Looks like a comma is searched for as a file separator.

**Comment by maltaisn** [comment]
Just saw this. I fixed it.
