### ISSUE TITLE
Incapable of passing an ordered list of individual items to be merged converted to a pdf file 

### ISSUE THREAD

**Issue by kqvanity** [maltaisn/swf-convert#5]
As far as i can understand the only way to pass file
- use a directory with a list of files then specify one single output file 
- pass each input with respective output i.e. `command pdf file1 file2 file3 -o outpout1.pdf output2.pdf output3.pdf` , or i'll be prompted with the error message `ERROR: Expected as many output files or directories as input.`

Is there a way to pass only the list of input items with just one single output name ?

**Comment by maltaisn** [comment]
No, as far as I remember this isn't possible. I could change it so that if there's one output and multiple inputs it works.

**Comment by kqvanity** [comment]
ya adding this feature would be really convenient .
